pub mod static_data {

    pub struct TradePile {
        pub items: Vec<String>,
    }
    impl TradePile {
        pub fn new() -> Self {
            TradePile {
                items: vec![
                    "Active Shielding Charge",
                    "Armor Energizing Charge",
                    "Armor Reinforcement Charge",
                    "Barrage L",
                    "Barrage M",
                    "Baryon Exotic Plasma M",
                    "Baryon Exotic Plasma S",
                    "Blood Radio L",
                    "Caldari Navy Antimatter Charge M",
                    "Caldari Navy Antimatter Charge L",
                    "Caldari Navy Inferno Cruise Missile",
                    "Caldari Navy Inferno Heavy Assault Missile",
                    "Caldari Navy Inferno Heavy Missile",
                    "Caldari Navy Inferno Light Missile",
                    "Caldari Navy Inferno Torpedo",
                    "Caldari Navy Iridium Charge L",
                    "Caldari Navy Iridium Charge M",
                    "Caldari Navy Iron Charge M",
                    "Caldari Navy Mjolnir Cruise Missile",
                    "Caldari Navy Mjolnir Heavy Missile",
                    "Caldari Navy Mjolnir Torpedo",
                    "Caldari Navy Scourge Heavy Missile",
                    "Caldari Navy Scourge Light Missile",
                    "Caldari Navy Nova Heavy Missile",
                    "Caldari Navy Nova Light Missile",
                    "Caldari Navy Nova Torpedo",
                    "Caldari Navy Nova Heavy Assault Missile",
                    "Caldari Navy Scourge Torpedo",
                    "Caldari Navy Thorium Charge M",
                    "Uncommon Moon Mining Crystal Type B II",
                    "Uncommon Moon Mining Crystal Type B I",
                    "Uncommon Moon Mining Crystal Type A II",
                    "Rare Moon Mining Crystal Type B II",
                    "Complex Asteroid Mining Crystal Type A II",
                    "Complex Asteroid Mining Crystal Type B I",
                    "Complex Asteroid Mining Crystal Type B II",
                    "Complex Asteroid Mining Crystal Type C II",
                    "Conflagration L",
                    "Conflagration XL",
                    "Electronic Hardening Charge",
                    "Electronic Superiority Charge",
                    "Sensor Optimization Charge",
                    "GalvaSurge Condenser Pack M",
                    "BlastShot Condenser Pack M",
                    "StrikeSnipe Ultra M",
                    "Imperial Navy Gamma L",
                    "Imperial Navy Microwave L",
                    "Imperial Navy Multifrequency M",
                    "Imperial Navy Radio L",
                    "Imperial Navy Standard L",
                    "Imperial Navy Ultraviolet L",
                    "Imperial Navy Xray L",
                    "Inferno Fury Heavy Missile",
                    "Inferno Precision Cruise Missile",
                    "Inferno Rage Heavy Assault Missile",
                    "Inferno Rage Torpedo",
                    "Javelin L",
                    "Mercoxit Asteroid Mining Crystal Type A I",
                    "Meson Exotic Plasma M",
                    "Mining Equipment Preservation Charge",
                    "Mining Laser Field Enhancement Charge",
                    "Mining Laser Optimization Charge",
                    "Mjolnir Fury Cruise Missile",
                    "Mjolnir Javelin Heavy Assault Missile",
                    "Nova Rage Torpedo",
                    "Mjolnir Javelin Torpedo",
                    "Mjolnir Precision Cruise Missile",
                    "Mjolnir Rage Heavy Assault Missile",
                    "Common Moon Mining Crystal Type B I",
                    "Navy Cap Booster 400",
                    "Navy Cap Booster 800",
                    "Nova Fury Light Missile",
                    "Null L",
                    "Null M",
                    "Quake L",
                    "Quake M",
                    "ECCM Script",
                    "Rapid Repair Charge",
                    "Republic Fleet Carbonized Lead L",
                    "Republic Fleet Carbonized Lead M",
                    "Republic Fleet Depleted Uranium M",
                    "Republic Fleet Fusion M",
                    "Republic Fleet Proton M",
                    "Republic Fleet EMP M",
                    "Republic Fleet Titanium Sabot M",
                    "Republic Fleet Phased Plasma M",
                    "Scorch XL",
                    "Scourge Rage Heavy Assault Missile",
                    "Large Armor Repairer II",
                    "Shield Extension Charge",
                    "Shield Harmonizing Charge",
                    "Sisters Core Scanner Probe",
                    "Sisters Combat Scanner Probe",
                    "Stasis Webification Probe",
                    "Caldari Navy Scourge Cruise Missile",
                    "Tremor L",
                    "Tremor M",
                    "Hail L",
                    "Void L",
                    "Void M",
                    "Rapid Deployment Charge",
                    "Interdiction Maneuvers Charge",
                    "Evasive Maneuvers Charge",
                    "Navy Cap Booster 150",
                    "Navy Cap Booster 3200",
                    "ElectroPunch Ultra M",
                    "Warp Disrupt Probe",
                    "Focused Void Bomb",
                    "Shrapnel Bomb",
                    "Occult S",
                    "GalvaSurge Condenser Pack L",
                    "Caldari Navy Thorium Charge L",
                    "Mercoxit Asteroid Mining Crystal Type A II",
                    "Caldari Navy Nova Cruise Missile",
                    "Inferno Fury Cruise Missile",
                    "Mjolnir Fury Cruise Missile",
                    "Nova Fury Cruise Missile",
                    "Scourge Fury Cruise Missile",
                    "Antipharmakon Aeolis",
                    "Strong Blue Pill Booster",
                    "Agency 'Pyrolancea' DB3 Dose I",
                    "Synth Blue Pill Booster",
                    "Synth Exile Booster",
                    "Standard Exile Booster",
                    "Standard Mindflood Booster",
                    "Quafe Zero Classic",
                    "Synth X-Instinct Booster",
                    "Antipharmakon Iokira",
                    "Agency 'Overclocker' SB3 Dose I",
                    "Agency 'Overclocker' SB5 Dose II",
                    "Agency 'Overclocker' SB7 Dose III",
                    "Agency 'Pyrolancea' DB5 Dose II",
                    "Agency 'Pyrolancea' DB7 Dose III",
                    "Agency 'Pyrolancea' DB9 Dose IV",
                    "Agency 'Hardshell' TB5 Dose II",
                    "Agency 'Hardshell' TB7 Dose III",
                    "Agency 'Hardshell' TB3 Dose I",
                    "Agency 'Overclocker' SB9 Dose IV",
                    "Synth Crash Booster",
                    "Agency 'Hardshell' TB9 Dose IV",
                    "'Augmented' Mining Drone",
                    "'Excavator' Mining Drone",
                    "'Excavator' Ice Harvesting Drone",
                    "'Integrated' Praetor",
                    "Acolyte II",
                    "Ametat II",
                    "Caldari Navy Warden",
                    "Equite II",
                    "Ogre II",
                    "Federation Navy Ogre",
                    "Gecko",
                    "Gram I",
                    "Caldari Navy Wasp",
                    "Light Hull Maintenance Bot I",
                    "Light Armor Maintenance Bot I",
                    "Heavy Armor Maintenance Bot I",
                    "Heavy Armor Maintenance Bot II",
                    "Heavy Shield Maintenance Bot I",
                    "Heavy Shield Maintenance Bot II",
                    "Heavy Hull Maintenance Bot I",
                    "Heavy Hull Maintenance Bot II",
                    "Hornet EC-300",
                    "Hornet II",
                    "Imperial Navy Acolyte",
                    "Imperial Navy Curator",
                    "Imperial Navy Infiltrator",
                    "Imperial Navy Praetor",
                    "Malleus II",
                    "Mining Drone I",
                    "Mining Drone II",
                    "Republic Fleet Berserker",
                    "Republic Fleet Bouncer",
                    "Republic Fleet Valkyrie",
                    "Republic Fleet Warrior",
                    "Warrior II",
                    "Salvage Drone I",
                    "Salvage Drone II",
                    "Templar I",
                    "Valkyrie II",
                    "Valkyrie SW-600",
                    "Vespa EC-600",
                    "Warden II",
                    "Gram II",
                    "Curator II",
                    "Berserker II",
                    "Genolution Core Augmentation CA-1",
                    "Genolution Core Augmentation CA-2",
                    "Genolution Core Augmentation CA-3",
                    "Genolution Core Augmentation CA-4",
                    "Inherent Implants 'Noble' Hull Upgrades HG-1003",
                    "Inherent Implants 'Noble' Mechanic MC-803",
                    "Inherent Implants 'Noble' Repair Proficiency RP-903",
                    "Inherent Implants 'Squire' Capacitor Management EM-803",
                    "Inherent Implants 'Squire' Capacitor Systems Operation EO-602",
                    "Inherent Implants 'Squire' Capacitor Systems Operation EO-603",
                    "Inherent Implants 'Squire' Power Grid Management EG-602",
                    "Zainou 'Gypsy' CPU Management EE-602",
                    "Information Command Mindlink",
                    "Shield Command Mindlink",
                    "Zainou 'Gnome' Shield Management SM-703",
                    "Poteque 'Prospector' Environmental Analysis EY-1005",
                    "Eifyr and Co. 'Gunslinger' Surgical Strike SS-903",
                    "Zainou 'Snapshot' Cruise Missiles CM-602",
                    "Zainou 'Gnome' Shield Management SM-703",
                    "Zainou 'Gypsy' Long Range Targeting LT-802",
                    "Zainou 'Deadeye' Target Navigation Prediction TN-902",
                    "Zainou 'Deadeye' Rapid Launch RL-1002",
                    "Ocular Filter - Standard",
                    "Ocular Filter - Improved",
                    "Ocular Filter - Basic",
                    "Memory Augmentation - Standard",
                    "Memory Augmentation - Improved",
                    "Memory Augmentation - Basic",
                    "Neural Boost - Standard",
                    "Neural Boost - Improved",
                    "Neural Boost - Basic",
                    "Cybernetic Subprocessor - Standard",
                    "Cybernetic Subprocessor - Improved",
                    "Cybernetic Subprocessor - Basic",
                    "Social Adaptation Chip - Standard",
                    "Social Adaptation Chip - Improved",
                    "Social Adaptation Chip - Basic",
                    "High-grade Crystal Alpha",
                    "High-grade Crystal Beta",
                    "High-grade Crystal Gamma",
                    "High-grade Crystal Delta",
                    "High-grade Crystal Epsilon",
                    "High-grade Crystal Omega",
                    "Mid-grade Crystal Alpha",
                    "Mid-grade Crystal Beta",
                    "Mid-grade Crystal Gamma",
                    "Mid-grade Crystal Delta",
                    "Mid-grade Crystal Epsilon",
                    "Mid-grade Crystal Omega",
                    "Genolution Core Augmentation CA-1",
                    "Genolution Core Augmentation CA-4",
                    "Genolution Core Augmentation CA-3",
                    "Genolution Core Augmentation CA-2",
                    "Mid-grade Amulet Alpha",
                    "Mid-grade Amulet Beta",
                    "Mid-grade Amulet Gamma",
                    "Mid-grade Amulet Gamma",
                    "Mid-grade Amulet Epsilon",
                    "Mid-grade Amulet Omega",
                    "Inherent Implants 'Noble' Remote Armor Repair Systems RA-703",
                    "Inherent Implants 'Noble' Mechanic MC-803",
                    "Inherent Implants 'Noble' Repair Proficiency RP-903",
                    "Inherent Implants 'Noble' Hull Upgrades HG-1003",
                    "Inherent Implants 'Noble' Hull Upgrades HG-1005",
                    "Inherent Implants 'Squire' Capacitor Systems Operation EO-603",
                    "Inherent Implants 'Squire' Power Grid Management EG-601",
                    "Inherent Implants 'Squire' Power Grid Management EG-602",
                    "Inherent Implants 'Squire' Power Grid Management EG-603",
                    "Zainou 'Gypsy' CPU Management EE-601",
                    "Zainou 'Gypsy' CPU Management EE-602",
                    "Zainou 'Gypsy' CPU Management EE-603",
                    "Inherent Implants 'Squire' Capacitor Management EM-803",
                    "Inherent Implants 'Squire' Capacitor Management EM-805",
                    "Armored Command Mindlink",
                    "Information Command Mindlink",
                    "Mining Foreman Mindlink",
                    "Shield Command Mindlink",
                    "Skirmish Command Mindlink",
                    "Eifyr and Co. 'Gunslinger' Motion Prediction MR-703",
                    "Eifyr and Co. 'Gunslinger' Surgical Strike SS-903",
                    "Zainou 'Deadeye' Sharpshooter ST-903",
                    "Inherent Implants 'Lancer' Large Energy Turret LE-1003",
                    "Zainou 'Deadeye' Missile Projection MP-703",
                    "Zainou 'Snapshot' Heavy Missiles HM-703",
                    "Zainou 'Deadeye' Guided Missile Precision GP-803",
                    "Zainou 'Deadeye' Guided Missile Precision GP-805",
                    "Zainou 'Deadeye' Target Navigation Prediction TN-903",
                    "Zainou 'Deadeye' Target Navigation Prediction TN-905",
                    "Zainou 'Deadeye' Rapid Launch RL-1003",
                    "Zainou 'Deadeye' Rapid Launch RL-1005",
                    "Eifyr and Co. 'Rogue' Navigation NN-603",
                    "Eifyr and Co. 'Rogue' Warp Drive Speed WS-610",
                    "Eifyr and Co. 'Rogue' Evasive Maneuvering EM-703",
                    "Zor's Custom Navigation Hyper-Link",
                    "Eifyr and Co. 'Alchemist' Biology BY-810",
                    "Zainou 'Beancounter' Reprocessing RX-804",
                    "Inherent Implants 'Highwall' Mining MX-1003",
                    "Inherent Implants 'Highwall' Mining MX-1005",
                    "Poteque 'Prospector' Astrometric Pinpointing AP-606",
                    "Poteque 'Prospector' Astrometric Rangefinding AR-806",
                    "Neural Lace 'Blackglass' Net Intrusion 920-40",
                    "Poteque 'Prospector' Environmental Analysis EY-1005",
                    "Zainou 'Gnome' Shield Management SM-703",
                    "Zainou 'Gnome' Shield Operation SP-903",
                    "AE-K Compact Drone Damage Amplifier",
                    "ORE Ice Harvester",
                    "ORE Strip Miner",
                    "Dread Guristas Drone Damage Amplifier",
                    "Drone Link Augmentor I",
                    "Fighter Support Unit II",
                    "Medium Knave Scoped Energy Nosferatu",
                    "Small Energy Neutralizer II",
                    "Covert Ops Cloaking Device II",
                    "Prototype Cloaking Device I",
                    "Sensor Booster II",
                    "Large Shield Extender II",
                    "Caldari Navy Medium Shield Extender",
                    "Small Shield Extender II",
                    "Micro Auxiliary Power Core II",
                    "Domination Heavy Stasis Grappler",
                    "Domination Warp Disruptor",
                    "Dread Guristas Multispectral ECM",
                    "Dread Guristas Stasis Webifier",
                    "Federation Navy Stasis Webifier",
                    "Stasis Webifier II",
                    "Heavy Stasis Grappler II",
                    "Heavy Warp Disruptor I",
                    "Interdiction Sphere Launcher I",
                    "Large Remote Armor Repairer II",
                    "Multispectral ECM II",
                    "Multispectrum Energized Membrane II",
                    "Republic Fleet Target Painter",
                    "Republic Fleet Warp Disruptor",
                    "Shadow Serpentis Heavy Stasis Grappler",
                    "Target Painter II",
                    "Cap Recharger II",
                    "Warp Disruption Field Generator II",
                    "Warp Scrambler II",
                    "Heavy Energy Neutralizer II",
                    "Medium Energy Neutralizer II",
                    "5MN Y-T8 Compact Microwarpdrive",
                    "5MN Quad LiF Restrained Microwarpdrive",
                    "5MN Microwarpdrive II",
                    "Coreli A-Type 5MN Microwarpdrive",
                    "Expanded Cargohold II",
                    "Nanofiber Internal Structure II",
                    "Modulated Strip Miner II",
                    "Modulated Deep Core Strip Miner II",
                    "Mining Laser Upgrade II",
                    "Ice Harvester Upgrade II",
                    "Bomb Launcher I",
                    "Bomb Launcher II",
                    "150mm Railgun II",
                    "150mm Prototype Gauss Gun",
                    "Small Focused Beam Laser II",
                    "Crosslink Compact Ballistic Control System",
                    "Heavy Missile Launcher II",
                    "'Arbalest' Heavy Missile Launcher",
                    "'Arbalest' Rapid Heavy Missile Launcher I",
                    "Torpedo Launcher II",
                    "Prototype 'Arbalest' Torpedo Launcher",
                    "Information Command Burst II",
                    "Mining Foreman Burst I",
                    "Assault Damage Control II",
                    "Co-Processor II",
                    "Warp Scrambler II",
                    "Republic Fleet Medium Shield Extender",
                    "Enduring Multispectrum Shield Hardener",
                    "Skirmish Command Burst II",
                    "Small S95a Scoped Remote Shield Booster",
                    "Capacitor Power Relay II",
                    "Gyrostabilizer II",
                    "Tracking Enhancer II",
                    "720mm Howitzer Artillery II",
                    "True Sansha Warp Disruptor",
                    "Large Azeotropic Restrained Shield Extender",
                    "Large Ancillary Remote Shield Booster",
                    "Large Murky Compact Remote Shield Booster",
                    "200mm Steel Plates II",
                    "CONCORD Capital Shield Booster",
                    "Covert Jump Portal Generator I",
                    "Mega Pulse Laser II",
                    "Astero",
                    "Caldari Navy Hookbill",
                    "Federation Navy Comet",
                    "Garmur",
                    "Harpy",
                    "Hawk",
                    "Imperial Navy Slicer",
                    "Republic Fleet Firetail",
                    "Taranis",
                    "Confessor",
                    "Hecate",
                    "Council Diplomatic Shuttle",
                    "Svipul",
                    "Retribution",
                    "Small Hybrid Burst Aerator II",
                    "Small EM Shield Reinforcer II",
                    "Small Core Defense Field Extender II",
                    "Pure Standard Mindflood Booster",
                    "Datacore - Graviton Physics",
                    "Datacore - Molecular Engineering",
                    "Datacore - Electronic Engineering",
                    "Fierce Gamma Filament",
                    "Noise-25 'Needlejack' Filament",
                    "Raging Exotic Filament",
                    "Chaotic Exotic Filament",
                    "Raging Electrical Filament",
                    "Signal-25 'Needlejack' Filament",
                    "Raging Electrical Filament",
                    "Raging Dark Filament",
                ]
                .into_iter()
                .map(|s| s.to_owned())
                .collect(),
            }
        }
    }
}
